### ISSUE TITLE
java.lang.NullPointerException: Lot of different failures related to Locker UI

### ISSUE THREAD

**Issue by dvobecky** [Ceskasporitelna/cs-locker-ui-sdk-droid#14]
Recently we got negative feedback on our app Friends 24. The client said that the application failed several times during fingerprint login. Obviously it has someting to do with Locker UI. Especially when we saw its Android Vitals we had a reason to think so. Strange thing is that when we saw Android Vitals like 2 weeks ago there was not a single failure (using last 7 days filter) and suddenly several appeared just now.

By the way there are like hundreds of similar or the same failures in relation to our other app George Go. That looks far more critical so we should deal with it.

## Locker UI version
compile ‘cz.csas:cs-core-sdk:1.1.1@aar’
compile ‘cz.csas:cs-locker-ui-sdk:1.1.2@aar’

## Most common failure:
- at **cz.csas.lockerui.MainActivity.onCreate**

**java.lang.RuntimeException:** 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2695)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2769)
  at android.app.ActivityThread.access$900 (ActivityThread.java:177)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1430)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:135)
  at android.app.ActivityThread.main (ActivityThread.java:5910)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1405)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1200)
**Caused by: java.lang.NullPointerException:** 
  at cz.csas.lockerui.MainActivity.onCreate (MainActivity.java:77)
  at android.app.Activity.performCreate (Activity.java:6178)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1118)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2648)

## Android Vitals of Friends 24 & George Go
- George Go Google Play Console **Android Vitals**
![georgego-failing](https://user-images.githubusercontent.com/32513603/31175339-4900aa7e-a90f-11e7-958b-4fde7a675aa9.png)
- Friends 24 Google Play Console **Android Vitals**
![friends24-failing](https://user-images.githubusercontent.com/32513603/31175328-3bc07f56-a90f-11e7-97f8-ef5266dca704.png)
*related to Locker UI

**Comment by hauseja3** [comment]
@dvobecky Thank you for your report, I will analyze the errors you suggested.
It is also possible, that some of them were already fixed, because the sdk version you mentioned are quiet old.

**Comment by dvobecky** [comment]
@hauseja3 Thanks a lot. If anything, I am always happy to help :+1:

**Comment by hauseja3** [comment]
@dvobecky can I get access to your android vitals console, please? It would be more straightforward to check and solve locker related bugs.

**Comment by dvobecky** [comment]
@hauseja3 I'm sorry, but I don't have admin permissions :disappointed: I'll get the access for you tomorrow, ok? Just need your email

**Comment by hauseja3** [comment]
@dvobecky you pbbly need my Gmail, right?

hauseja3@gmail.com

**Comment by hauseja3** [comment]
@dvobecky I found there one main error, I cannot really reproduce. I am not sure, how it could happen, but I added some safe checks. Can you please show me how you initialize `LockerUI` and also how you start it?

The other errors were already mitigated in new versions, actual version is v2.0.2.

**Comment by hauseja3** [comment]
@dvobecky ??

**Comment by dvobecky** [comment]
I can resend you from one of our programmers how it works with Friends 24 app:

```
this.context = context;
       mAuthFlowOptions = new AuthFlowOptions.Builder().setSkipStatusScreen(SkipStatusScreen.ALWAYS).setRegistrationScreenText(context.getString(R.string.registration_screen_text)).setLockedScreenText(context.getString(R.string.locked_screen_text)).setOfflineAuthEnabled().create();
       mDisplayInfoOptions = new DisplayInfoOptions(“”);

       if (!isLockerAvailable()) {
           LockerConfig lockerConfig = new LockerConfig.Builder()
                   .setClientId(CLIENT_ID)
                   .setClientSecret(CLIENT_SECRET)
                   .setPublicKey(PUBLIC_KEY)
                   .setRedirectUrl(REDIRECT_URL)
                   .setScope(SCOPE).setOfflineAuthEnabled()
                   .create();

           CoreSDK.getInstance()
                   .useContext(App.get())
                   .useWebApiKey(WEB_API_KEY)
                   .useLogger(new LogManagerImpl(“CS_LOG”, LogLevel.DEBUG))
                   .useEnvironment(new Environment(BASE_URL, BASE_URL_OAUTH, false))
                   .useLocker(lockerConfig);

           List<LockType> lockTypes = new ArrayList<>();
           lockTypes.add(new GestureLock(3, 4));
           lockTypes.add(new PinLock(4));
           lockTypes.add(new FingerprintLock());
           lockerUIOptions = new LockerUIOptions.Builder()
                   .setNavBarColor(CsNavBarColor.DEFAULT)
                   .setShowLogo(ShowLogo.EXCEPT_REGISTRATION)
                   .setAllowedLockTypes(lockTypes)
                   .setAppName(App.get().getString(R.string.application_name))
                   .create();

           FAUtils.logEvent(FAUtils.LOCKER_INIT);
           LockerUI.getInstance().initialize(context, lockerUIOptions);
```

After the activity starts in onResume in case of a locked Locker we call:

```
if (lockerState == State.USER_UNREGISTERED || lockerState == State.USER_LOCKED) {
           // offline verification settings
           FAUtils.logEvent(FAUtils.LOCKER_START_AUTH);
           mAuthFlowOptions.setOfflineAuthEnabled(mOfflineAuthEnabled);
           LockerUI.getInstance().startAuthenticationFlow(mAuthFlowOptions, callbackUI);
```

**Comment by hauseja3** [comment]
@dvobecky it looks ok. Because I cannot really reproduce this type of error, I would recommend this.  
I added safety checks to potentially mitigate this frequent error. Can you please update your core+locker versions to:

`cz.csas:cs-core-sdk:1.3.3@aar`
`cz.csas:cs-locker-ui-sdk:2.0.3@aar`

and release new build with these new versions.

I would like to monitor Android Vitals and see if it was mitigated or not. Is it possible, please?

**Comment by dvobecky** [comment]
@hauseja3 Sure. The problem is that we cannot do that earlier than the planned release of Friends 24 production app (probably in 3 or 4 weeks). Is that OK with you? 

Unfortunately, I can speak only on behalf of Friends 24 development team. Can't tell you how is it with George Go. Should I try to contact someone?

**Comment by hauseja3** [comment]
@dvobecky I think that the earlier release, the better. But I understand your schedule. 

If you wouldn't mind, please try to contact them with the information about updating sdk versions.
