### ISSUE TITLE
Enable to skip the security method screen

### ISSUE THREAD

**Issue by arhus** [Ceskasporitelna/cs-locker-ui-sdk-droid#18]
The registration process requires the user to select at least one security method with "no security method" being one of them. There is a use case in some of our apps where "no security method" is the only option. Such a screen becomes redundant as the user has no other option to select.

Please enable the Locker UI to skip the screen and select "no security method" as the desired option by default. 

![screenshot_20171020-084726](https://user-images.githubusercontent.com/6939571/37965005-d138e270-31c3-11e8-868d-8b941394b3d2.png)

**Comment by hauseja3** [comment]
Solved in https://github.com/Ceskasporitelna/cs-locker-ui-sdk-droid/pull/25
