### ISSUE TITLE
Preklep v stringoch

### ISSUE THREAD

**Issue by kvarackova** [Ceskasporitelna/cs-locker-ui-sdk-droid#2]
![screenshot_20170511-124228](https://cloud.githubusercontent.com/assets/24827646/26046611/0ad31b1c-3950-11e7-8ac0-c62851f8adad.png)

Pls, v textacii je drobny preklep - chyba krouzek nad u.

**Comment by kirscfil** [comment]
Dobrý den, děkuji za nahlášení chyby, urychleně zařídíme její nápravu.

**Comment by jmachan** [comment]
@kirscfil zároveň prosím o opravu "Př**í**hlášení" na "Př**i**hlášení"
