### ISSUE TITLE
prihlasenie + chyba namiesto registracie po preinstalovani

### ISSUE THREAD

**Issue by kvarackova** [Ceskasporitelna/cs-locker-ui-sdk-droid#21]
V appke MujStav som si vsimla nasledovne zahadne chovanie a nie som jedina, hlasia to aj ludia z bety a produkcie.

Normalne pouzivam MujStav, odinstalujem, nainstalujem znova z google play storu, aplikacia sa spusti a chce po mne prihlasenie poslednou pouzivanou metodou. Zazila som to pre odtlacok aj pre gesto alebo pin (jedno z tych dvoch, ale nepamatam si ktore), takze tam asi rozdiel nebude. 

Myslim, ze po odintalovani by sa vsetky tieto udaje mali zmazat, netusim, odkial ich pak locker berie, pretoze ponuka fakt tu metodu zabezpecenia, ktoru som mala pred odinstalovanim. A hlavne, po zadani spravneho paternu alebo prilozeni prstu mi appka napise, ze bol prekroceny pocet pokusov o prihlasenie a odregistruje ma. Pricom pokus prebehol iba jeden jediny.

Nevsimla som si, ze by sa to dialo na nejakom konkretnom mobile alebo androide, vacsinu casu mam android 8 alebo 7. 
Aplikaciu MujStav neupgradujem, instalujem rovnaku verziu ako som odisntalovala 1.9.2, netusim ci spolu suvisi.

**Comment by kvarackova** [comment]
Podarilo sa mi chybu uplnou nahodou nasimulovat:
- nainstalujem MujStav, zaregistrujem sa, pouzivam
- odinstalujem MujStav
- nainstalujem znova a toto tu mi vracia USER_LOCKED namiesto  USER_UNREGISTERED:
LockerUI.getInstance().getLocker().getStatus().getState()

LockerStatus ma nastaveny lockType aj clientId, co si myslim, ze by po odinstalovani appky malo byt premazane

**Comment by kvarackova** [comment]
Vyriesene nastavenim v manifeste aplikacie:
android:allowBackup="false"
tools:replace="allowBackup"

Netusim ale ako je mozne, ze sa to prejavilo az teraz. V manifeste aplikacie doteraz tieto dva riadky neboli (v lockeri je iba allowBackup false) a az po predoslu verziu sa spravala aplikacia korektne..

**Comment by hauseja3** [comment]
@kvarackova díky za info.
