### ISSUE TITLE
unlock a OTP unlock

### ISSUE THREAD

**Issue by kvarackova** [Ceskasporitelna/cs-locker-ui-sdk-droid#23]
Nase aplikacia umoznuje pridat na homescreen widget. Aby zostatok mohol byt zobrazeny, na pozadi sa vykona unlockWithOneTimePassword, ktory unlocknelocker. 

Bolo by mozne rozlisovat, ci bol urobeny klasicky unlock (pomocou zabezpecovacej metody) alebo OTP unlock? Potrebovali by sme, aby po OTP unlocku bol locker aj nadalej locknuty (vracal stav USER_LOCKED) a teda nutil uzivatela prejst zabezpecenim.

**Comment by hauseja3** [comment]
@kvarackova toto se týká spíše `core-sdk`, proto migruji tam (https://github.com/Ceskasporitelna/cs-core-sdk-droid/issues/20)
