### ISSUE TITLE
Locker Listener not immediately called on Backbutton

### ISSUE THREAD

**Issue by bbindreiter** [Ceskasporitelna/cs-locker-ui-sdk-droid#5]
See this Jira-Ticket please
https://issues.beeone.at/browse/GGINTL-235

First click on back button does nothing. Second click then calls the success method on our listener. It would be great if the first click does it already.

Locker UI SDK: 0.17.11
Core SDK: 0.19.3

**Comment by hauseja3** [comment]
@bbindreiter could you please provide whole the issue description? (I don't have access to that issue at the moment) 

Thank you in advance.

**Comment by bbindreiter** [comment]
new link: https://issues.beeone.at/browse/GRCZ-5606

**Comment by hauseja3** [comment]
@bbindreiter I am sorry, maybe it is my mistake. Please do not outsource the issue description. Could you rewrite it here, instead of posting an external link, please?

**Comment by hauseja3** [comment]
@bbindreiter Almost no description provided. I cannot solve this issue with only this kind of description:

"First click on back button does nothing. Second click then calls the success method on our listener. It would be great if the first click does it already."

Please provide more detailed one.

**Comment by bbindreiter** [comment]
Start up Locker to see the Login-Screen as shown in the screenshot: 
![screenshot_20170420-140438](https://cloud.githubusercontent.com/assets/3252801/26828345/5832bfb6-4ac1-11e7-8925-60f5240737f7.png)

When hitting the back button on the phone for the first time nothing happens. After clicking it again the activity is closed and the success() method from our CallbackUI<LockerStatus> Listener is called. It should be called on the first click already.

Tested with:
Locker UI SDK: 0.17.11
Core SDK: 0.19.3
