### ISSUE TITLE
locker neposiela UNREGISTER stav

### ISSUE THREAD

**Issue by kvarackova** [Ceskasporitelna/cs-locker-ui-sdk-droid#6]
Locker od v1.1.1 (cz.csas:cs-locker-ui-sdk:1.1.1@aar) prestal posielat unregister stav. Pls mrknite na to asap.

**Comment by kirscfil** [comment]
@kvarackova: Zdravím, děkuji za nahlášení chyby. Budeme se jí věnovat, jakmile to bude možné.
