### ISSUE TITLE
Navigation bar color

### ISSUE THREAD

**Issue by hauseja3** [Ceskasporitelna/cs-locker-ui-sdk-droid#7]
Make it possible to change navigation bar color & tint color via `LockerUIOptions`

**Comment by nevyhostenyv** [comment]
Currently, there is possible to set the LockerUIOptions.navBarColor to default or white. You need to set the navBarColor to any color?
And regarding the tint color, adding UINavigationBar.appearance.setTintColor() in the application delegate solves not this issue?

**Comment by hauseja3** [comment]
@nevyhostenyv u are at the wrong platform. Please write it to https://github.com/Ceskasporitelna/cs-locker-ui-sdk-ios/issues/3 and reference vratislav.
